// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAyjRmLyBJyiA7dfhqwLy80gCVx59QVMI',
    appId: '1:402773067153:web:1d77c39784ebfafb0f4630',
    messagingSenderId: '402773067153',
    projectId: 'meeting-app-930c0',
    authDomain: 'meeting-app-930c0.firebaseapp.com',
    storageBucket: 'meeting-app-930c0.appspot.com',
    measurementId: 'G-8SR1B1QVDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZXwMBovatSycgV1lesx-tIntNKpTeJ4I',
    appId: '1:402773067153:android:b01e7bdd181ecf6d0f4630',
    messagingSenderId: '402773067153',
    projectId: 'meeting-app-930c0',
    storageBucket: 'meeting-app-930c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj7cryhpuY0Wrnpe7UErYugL0jARxup3k',
    appId: '1:402773067153:ios:7f2dd9c4d011bbe20f4630',
    messagingSenderId: '402773067153',
    projectId: 'meeting-app-930c0',
    storageBucket: 'meeting-app-930c0.appspot.com',
    androidClientId: '402773067153-jll7arn0hlpp8bef3rsr79ev8d2ddfke.apps.googleusercontent.com',
    iosClientId: '402773067153-clgsv2bdbkkh5v21buf7raqa8pl99ilh.apps.googleusercontent.com',
    iosBundleId: 'com.example.meetingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj7cryhpuY0Wrnpe7UErYugL0jARxup3k',
    appId: '1:402773067153:ios:7f2dd9c4d011bbe20f4630',
    messagingSenderId: '402773067153',
    projectId: 'meeting-app-930c0',
    storageBucket: 'meeting-app-930c0.appspot.com',
    androidClientId: '402773067153-jll7arn0hlpp8bef3rsr79ev8d2ddfke.apps.googleusercontent.com',
    iosClientId: '402773067153-clgsv2bdbkkh5v21buf7raqa8pl99ilh.apps.googleusercontent.com',
    iosBundleId: 'com.example.meetingApp',
  );
}
